apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASS
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector: 
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

