apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: {{ .Values.grafana.replicas }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: {{ .Values.grafana.image }}
        imagePullPolicy: {{ .Values.grafana.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.grafana.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector: 
    app: grafana
  ports:
    - protocol: TCP
      port: {{ .Values.grafana.port }}
      targetPort: {{ .Values.grafana.port }}

