backend:
  image: go-backend
  replicas: 1
  port: 5000

mysql:
  image: registry.cn-hangzhou.aliyuncs.com/githubimage/mysql:8.0
  replicas: 1
  port: 3306

nginx:
  image: nginx
  replicas: 1
  port: 80

prometheus:
  image: prom/prometheus
  replicas: 1
  port: 9090
  imagePullPolicy: Never

grafana:
  image: grafana/grafana
  replicas: 1
  port: 3000
  imagePullPolicy: Never
